### PR TITLE
Add "in" to keywords and decrement indentation as "when"

### PR DESCRIPTION
**Pull request by RespiteSage**
I see that "when" is in the increment indent pattern; I'm not sure why, but maybe "in" will need to be added there, too?

### CODE REVIEW

**Comment by RespiteSage** [comment]
Is there a good way to test this on my local machine so I can verify that it fixes the disparity between `when` and `in`?

**Comment by maxbertinetti** [comment]
> Is there a good way to test this on my local machine so I can verify that it fixes the disparity between `when` and `in`?

A way is to clone locally, build the plugin (see [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)) and install the .vsix file.

image

or with
`code --install-extension myextension.vsix`

**Comment by RespiteSage** [comment]
I was able to test this PR like you described, and I found that I also needed to add "in" to the indentation increment list to get it to behave like "when". I also incremented the revision number, but I can undo that change if that's wrong.

**Review by maxbertinetti — COMMENTED** [review]
Ok

**Pull request merged**
